name: GitHub Profile Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ERRIFI-X
          template: classic
          base: header, activity, repositories
          filename: github-metrics.svg
          output_action: commit
          branch: output
